### ISSUE TITLE
Move to aura ?

### ISSUE THREAD

**Issue by harikt** [friendsofaura/Aura.Asset_Bundle#4]
Hi @pmjones , 

can we move this bundle to aura?

Are you done with the naming configuration , I feel we have done a mistake pushing the release of 2.0.0 without naming the services :-/ as mentioned on google groups.

aura/web:request like that .

**Comment by pmjones** [comment]
> I feel we have done a mistake pushing the release of 2.0.0 without naming the services :-/ as mentioned on google groups.

I realized that yesterday. :-/

2.1.0 releases next! ;-)

**Comment by harikt** [comment]
:+1:  .

**Comment by harikt** [comment]
@pmjones any thoughts on moving to the organization ? 

Somethings that need to address are 
1. Caching of the css / js after first request . Probably move / symlink to files .
